CREATE OR REPLACE VIEW DOGSENSE.ANALYTICS.DOG_STATE_HOURLY
COMMENT = 'Hourly state distribution by pseudonymous dog identifier'
AS
SELECT
    DOG_ID_HASH,
    DATE_TRUNC('hour', STARTED_AT) AS HOUR,
    STATE,
    COUNT(*) AS EVENT_COUNT,
    SUM(COALESCE(DURATION_SECONDS, 0)) AS TOTAL_DURATION_SECONDS,
    AVG(CONFIDENCE_AVG) AS AVG_CONFIDENCE,
    AVG(OBSERVATION_QUALITY_AVG) AS AVG_OBSERVATION_QUALITY,
    MAX(UPDATED_AT) AS LAST_UPDATED_AT
FROM DOGSENSE.BEHAVIOR.STATE_EVENTS
GROUP BY
    DOG_ID_HASH,
    DATE_TRUNC('hour', STARTED_AT),
    STATE;

