CREATE OR REPLACE VIEW DOGSENSE.ANALYTICS.DOG_STATE_DAILY
COMMENT = 'Daily behavior summary without household or camera identifiers'
AS
SELECT
    DOG_ID_HASH,
    TO_DATE(STARTED_AT) AS EVENT_DATE,
    COUNT(*) AS EVENT_COUNT,
    COUNT_IF(STATE = 'stress_signals') AS STRESS_SIGNAL_EVENT_COUNT,
    SUM(COALESCE(DURATION_SECONDS, 0)) AS MONITORED_EVENT_SECONDS,
    AVG(CONFIDENCE_AVG) AS AVG_CONFIDENCE,
    MAX(ENDED_AT) AS LAST_EVENT_ENDED_AT
FROM DOGSENSE.BEHAVIOR.STATE_EVENTS
GROUP BY DOG_ID_HASH, TO_DATE(STARTED_AT);

