-- DogSense Live / Snowflake migration 001
-- Run with a deployment role that may create DOGSENSE objects. Runtime writers
-- should receive privileges only on DOGSENSE.BEHAVIOR.STATE_EVENTS.

CREATE DATABASE IF NOT EXISTS DOGSENSE
    COMMENT = 'Pseudonymized behavioral analytics for DogSense Live';

CREATE SCHEMA IF NOT EXISTS DOGSENSE.BEHAVIOR
    COMMENT = 'Consolidated behavioral events; no video, frames or camera credentials';

CREATE SCHEMA IF NOT EXISTS DOGSENSE.ANALYTICS
    COMMENT = 'Read-only analytical views over pseudonymized events';

CREATE TABLE IF NOT EXISTS DOGSENSE.BEHAVIOR.STATE_EVENTS (
    EVENT_ID STRING NOT NULL,
    DOG_ID_HASH STRING NOT NULL,
    CAMERA_ID_HASH STRING,
    STARTED_AT TIMESTAMP_TZ NOT NULL,
    ENDED_AT TIMESTAMP_TZ,
    DURATION_SECONDS INTEGER,
    ACTIVITY STRING,
    STATE STRING NOT NULL,
    CONFIDENCE_AVG FLOAT,
    CONFIDENCE_MAX FLOAT,
    OBSERVATION_QUALITY_AVG FLOAT,
    SIGNALS VARIANT,
    PROMPT_VERSION STRING,
    MODEL_NAME STRING,
    PROCESSING_LATENCY_MS INTEGER,
    VOICE_ALERT_GENERATED BOOLEAN DEFAULT FALSE,
    SOLANA_NETWORK STRING,
    SOLANA_TRANSACTION_SIGNATURE STRING,
    EVENT_HASH STRING,
    CREATED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_STATE_EVENTS PRIMARY KEY (EVENT_ID) NOT ENFORCED,
    CONSTRAINT CK_EVENT_DURATION CHECK (DURATION_SECONDS IS NULL OR DURATION_SECONDS >= 0),
    CONSTRAINT CK_EVENT_STATE CHECK (
        STATE IN ('relaxed', 'engaged', 'alert', 'stress_signals', 'indeterminate')
    )
)
DATA_RETENTION_TIME_IN_DAYS = 1
COMMENT = 'Idempotently merged, pseudonymized state events. Raw inference media is prohibited.';

-- Optional P1 diagnostic table. It is transient and deliberately short-lived.
CREATE TRANSIENT TABLE IF NOT EXISTS DOGSENSE.BEHAVIOR.INFERENCE_SAMPLES (
    INFERENCE_ID STRING NOT NULL,
    DOG_ID_HASH STRING NOT NULL,
    CAPTURED_AT TIMESTAMP_TZ NOT NULL,
    ACTIVITY STRING,
    STATE STRING,
    CONFIDENCE FLOAT,
    QUALITY FLOAT,
    SIGNALS VARIANT,
    LATENCY_MS INTEGER,
    PROMPT_VERSION STRING,
    MODEL_NAME STRING,
    CREATED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_INFERENCE_SAMPLES PRIMARY KEY (INFERENCE_ID) NOT ENFORCED
)
DATA_RETENTION_TIME_IN_DAYS = 1
COMMENT = 'Optional short-lived metadata samples; never store pixels, base64, URLs or secrets.';
